# Generated by Django 5.0 on 2023-12-24 11:39

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notice',
            name='category',
            field=models.CharField(choices=[('Tanks', 'Танки'), ('Healers', 'Хилы'), ('DD', 'ДД'), ('Traders', 'Торговцы'), ('Guidemasters', 'Гилдмастеры'), ('Smiths', 'Кузнецы'), ('Tanners', 'Кожевники'), ('PotionMasters', 'Зельевары'), ('Spellmasters', 'Мастера заклинаний')], default='Tanks', max_length=18),
        ),
        migrations.AlterField(
            model_name='notice',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('undefined', 'Неопределенный'), ('accepted', 'Принят'), ('rejected', 'Отклонен')], default='undefined', max_length=10),
        ),
    ]
